#!/usr/bin/env python3
"""
Backfill missing per-approach solution code across required languages.

This script:
1) Scans all problems from seed_solutions (SOLUTIONS + RICH_SOLUTIONS)
2) Detects missing language blocks per approach after normalization/merge
3) Uses stage-2 code generation prompts to generate only missing cells
4) Writes an overlay module: backend/solution_code_multilang_autogen.py

The app loads this overlay automatically (when imported in solution_code_multilang.py),
so we do not need to edit massive seed dictionaries manually.
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import re
import sys
import time
from typing import Dict, Tuple, Any, List

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from seed_solutions import SOLUTIONS, RICH_SOLUTIONS, get_solutions_for_problem
from seed_starters import get_starters_for_problem
from solution_generation_pipeline import stage2_generate_code_for_cell
from solution_validator import REQUIRED_LANGS, CODE_KEY_BY_LANG, is_valid_code_snippet
from signature_contract import extract_signature, signatures_match
from solution_generation_pipeline import _call_llm_code, _strip_code_block


STATE_PATH = ROOT / "generated_solutions" / "multilang_autogen_state.json"
REPORT_PATH = ROOT / "generated_solutions" / "multilang_autogen_report.json"
OUTPUT_MODULE = ROOT / "solution_code_multilang_autogen.py"


def _approach_key(problem_title: str, approach_title: str) -> Tuple[str, str]:
    return (problem_title.strip(), (approach_title or "").strip().lower())


def _entry_key(problem_title: str, approach_title_lower: str) -> str:
    return f"{problem_title}||{approach_title_lower}"


def _from_entry_key(k: str) -> Tuple[str, str]:
    title, approach = k.split("||", 1)
    return title, approach


def _load_state() -> Dict[str, Dict[str, str]]:
    if not STATE_PATH.exists():
        return {}
    try:
        data = json.loads(STATE_PATH.read_text(encoding="utf-8"))
        if isinstance(data, dict):
            out: Dict[str, Dict[str, str]] = {}
            for k, v in data.items():
                if isinstance(k, str) and isinstance(v, dict):
                    out[k] = {str(kk): str(vv) for kk, vv in v.items() if isinstance(vv, str)}
            return out
    except Exception:
        pass
    return {}


def _save_state(state: Dict[str, Dict[str, str]]) -> None:
    STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
    STATE_PATH.write_text(json.dumps(state, indent=2), encoding="utf-8")


def _write_overlay_module(state: Dict[str, Dict[str, str]]) -> None:
    """
    Write python module:
      MULTILANG_AUTOGEN = { (title, approach_lower): {code_x: "...", ...}, ... }
    """
    lines: List[str] = []
    lines.append('"""')
    lines.append("Auto-generated supplemental solution code for missing languages.")
    lines.append("Generated by backend/scripts/backfill_solution_languages.py")
    lines.append('"""')
    lines.append("")
    lines.append("MULTILANG_AUTOGEN = {")

    for skey in sorted(state.keys()):
        title, approach = _from_entry_key(skey)
        cell = state[skey]
        if not cell:
            continue
        lines.append(f"    ({title!r}, {approach!r}): {{")
        for lang in REQUIRED_LANGS:
            code_key = CODE_KEY_BY_LANG[lang]
            if code_key in cell and (cell[code_key] or "").strip():
                lines.append(f"        {code_key!r}: {cell[code_key]!r},")
        lines.append("    },")

    lines.append("}")
    lines.append("")
    OUTPUT_MODULE.write_text("\n".join(lines), encoding="utf-8")


def _first_reference_code(app: Dict[str, Any]) -> str:
    ordered = (
        "code_python",
        "code_javascript",
        "code_java",
        "code_cpp",
        "code_go",
        "code_csharp",
        "code_c",
        "code",
    )
    for k in ordered:
        v = (app.get(k) or "").strip()
        if v:
            return v
    return ""


def _looks_like_language(code: str, lang: str) -> bool:
    """Heuristic guard to prevent obvious wrong-language snippets."""
    c = (code or "").strip()
    if not c:
        return False
    if lang == "python":
        return bool(re.search(r"^\s*(def|class)\s+\w+", c, re.MULTILINE))
    if lang == "javascript":
        return bool(re.search(r"\b(function|const|let|var)\b|=>", c))
    if lang == "java":
        return bool(re.search(r"\b(class|public)\b", c)) and "def " not in c
    if lang == "cpp":
        return bool(re.search(r"#include|using namespace std|std::|vector<|unordered_", c))
    if lang == "go":
        return bool(re.search(r"\bfunc\s+\w+\s*\(", c))
    if lang == "csharp":
        return bool(re.search(r"\b(class|public|private|protected|namespace)\b", c)) and "def " not in c
    return True


def _passes_signature_or_language_check(
    code: str,
    lang: str,
    starter_sig_snippet: str,
    allow_language_fallback: bool = False,
) -> bool:
    """
    Prefer signature check when starter signature is available.
    Otherwise fallback to language heuristics.
    """
    if not code or not is_valid_code_snippet(code):
        return False

    expected = extract_signature(starter_sig_snippet or "", lang) if starter_sig_snippet else None
    actual = extract_signature(code, lang)
    if expected is not None:
        if actual is None:
            return allow_language_fallback and _looks_like_language(code, lang)
        # Enforce callable compatibility; keep types lenient for non-registry starters.
        if signatures_match(
            expected,
            actual,
            strict_types=False,
            strict_param_names=False,
        ):
            return True
        return allow_language_fallback and _looks_like_language(code, lang)
    return _looks_like_language(code, lang)


def _translate_from_reference(
    problem_title: str,
    approach_title: str,
    language: str,
    signature_snippet: str,
    reference_code: str,
) -> str:
    """
    Fallback: ask model to translate known-good reference code into target language.
    """
    if not reference_code or len(reference_code.strip()) < 40:
        return ""
    system = (
        "You convert algorithm solutions between languages.\n"
        "Rules:\n"
        "- Output ONLY code in the requested language.\n"
        "- No markdown fences, no explanation.\n"
        "- Preserve algorithm and complexity.\n"
        "- Match the provided function/class signature style."
    )
    user = (
        f"Problem: {problem_title}\n"
        f"Approach: {approach_title}\n"
        f"Target language: {language}\n\n"
        f"Target signature/context:\n{(signature_snippet or '').strip()[:2000]}\n\n"
        f"Reference solution in another language:\n{reference_code[:4000]}\n"
    )
    raw = _call_llm_code(system, user, timeout=30)
    code = _strip_code_block(raw)
    return code.strip()


def main() -> int:
    parser = argparse.ArgumentParser(description="Backfill missing solution language blocks across all problems.")
    parser.add_argument("--max-cells", type=int, default=0, help="Generate at most N missing cells (0 = all).")
    parser.add_argument("--retries", type=int, default=3, help="Retries per missing cell.")
    parser.add_argument("--sleep-ms", type=int, default=0, help="Sleep between successful generations.")
    parser.add_argument("--reset", action="store_true", help="Ignore previous checkpoint state.")
    parser.add_argument("--titles", type=str, default="", help="Comma-separated problem titles to process.")
    parser.add_argument(
        "--allow-language-fallback",
        action="store_true",
        help="If signature does not match, accept snippets that strongly match target language syntax.",
    )
    args = parser.parse_args()

    state: Dict[str, Dict[str, str]] = {} if args.reset else _load_state()

    titles = sorted(set(SOLUTIONS.keys()) | set(RICH_SOLUTIONS.keys()))
    if args.titles.strip():
        wanted = {t.strip() for t in args.titles.split(",") if t.strip()}
        titles = [t for t in titles if t in wanted]

    generated = 0
    failed: List[Dict[str, str]] = []
    skipped_existing = 0
    total_missing_cells = 0

    print(f"[backfill] problems={len(titles)} reset={args.reset}", flush=True)
    for pi, title in enumerate(titles, start=1):
        sol = get_solutions_for_problem(title, enforce_signature=False) or {}
        approaches = sol.get("approaches") or []
        if not approaches:
            continue
        starters = get_starters_for_problem(title) or {}

        for ai, app in enumerate(approaches, start=1):
            app_title = app.get("title") or f"Approach {ai}"
            key_problem, key_approach = _approach_key(title, app_title)
            skey = _entry_key(key_problem, key_approach)
            state.setdefault(skey, {})
            entry = state[skey]

            intuition = (app.get("intuition") or app.get("content") or "").strip()
            algorithm = (app.get("algorithm") or app.get("content") or "").strip()
            ref_code = _first_reference_code(app)

            for lang in REQUIRED_LANGS:
                code_key = CODE_KEY_BY_LANG[lang]
                existing = (app.get(code_key) or "").strip()
                if existing:
                    continue
                total_missing_cells += 1
                if (entry.get(code_key) or "").strip():
                    skipped_existing += 1
                    continue

                if args.max_cells and generated >= args.max_cells:
                    print("[backfill] reached --max-cells limit")
                    _save_state(state)
                    _write_overlay_module(state)
                    report = {
                        "problems_processed": pi,
                        "generated_cells": generated,
                        "skipped_existing_in_state": skipped_existing,
                        "total_missing_cells_seen": total_missing_cells,
                        "failed": failed,
                    }
                    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
                    REPORT_PATH.write_text(json.dumps(report, indent=2), encoding="utf-8")
                    return 0

                base_sig = (starters.get(f"starter_code_{lang}") or "").strip()
                if not base_sig:
                    base_sig = (ref_code[:2000] or f"Implement {title} {app_title} in {lang}.")

                code = ""
                for attempt in range(1, args.retries + 1):
                    sig = base_sig
                    if attempt > 1 and ref_code:
                        sig = (
                            base_sig
                            + "\n\nReference solution logic in another language:\n"
                            + ref_code[:1800]
                        )
                    code = stage2_generate_code_for_cell(
                        problem_title=title,
                        approach_title=app_title,
                        intuition=intuition,
                        algorithm=algorithm,
                        language=lang,
                        signature_snippet=sig,
                    )
                    if code and _passes_signature_or_language_check(
                        code,
                        lang,
                        base_sig,
                        allow_language_fallback=args.allow_language_fallback,
                    ):
                        break
                    code = ""

                if not code and ref_code:
                    for _ in range(2):
                        tcode = _translate_from_reference(
                            problem_title=title,
                            approach_title=app_title,
                            language=lang,
                            signature_snippet=base_sig,
                            reference_code=ref_code,
                        )
                        if tcode and _passes_signature_or_language_check(
                            tcode,
                            lang,
                            base_sig,
                            allow_language_fallback=True,
                        ):
                            code = tcode
                            break

                if code:
                    entry[code_key] = code
                    generated += 1
                    print(f"[ok] {title} | {app_title} | {lang} ({generated})", flush=True)
                    if args.sleep_ms > 0:
                        time.sleep(args.sleep_ms / 1000.0)
                    if generated % 10 == 0:
                        _save_state(state)
                        _write_overlay_module(state)
                else:
                    failed.append(
                        {
                            "title": title,
                            "approach": app_title,
                            "language": lang,
                            "reason": "generation_failed_or_signature_mismatch",
                        }
                    )
                    print(f"[fail] {title} | {app_title} | {lang}", flush=True)

    _save_state(state)
    _write_overlay_module(state)
    report = {
        "problems_processed": len(titles),
        "generated_cells": generated,
        "skipped_existing_in_state": skipped_existing,
        "total_missing_cells_seen": total_missing_cells,
        "failed": failed,
    }
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(json.dumps(report, indent=2), encoding="utf-8")

    print("[done]", json.dumps({k: v for k, v in report.items() if k != "failed"}, indent=2), flush=True)
    print(f"[done] failed={len(failed)} report={REPORT_PATH}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
